#!/bin/bash

readonly BASE_DIR_PATH="$(pwd)"
SCRIPT_PARENT_DIR_PATH="$(dirname $0)"; cd "${SCRIPT_PARENT_DIR_PATH}"
readonly SCRIPT_PARENT_DIR_PATH="$(pwd)" ; cd "${BASE_DIR_PATH}"

set -u

cd "${SCRIPT_PARENT_DIR_PATH}/.."

echo -e "\n\n********************** AS THE MAN ON A NODE WITHOUT SLCS *************************\n\n"
nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini -a '!compute,!cog_create_user,!slcs' --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini -a '!compute,!cog_create_user,!slcs' --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini -a '!compute,!cog_create_user,!slcs' --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini -a '!compute,!cog_create_user,!slcs' --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini -a '!compute,!cog_create_user,!slcs' --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini -a '!compute,!cog_create_user,!slcs' --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini -a '!compute,!cog_create_user,!slcs' --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini -a '!compute,!cog_create_user,!slcs' --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini -a '!compute,!cog_create_user,!slcs' --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini -a '!compute,!cog_create_user,!slcs' --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini -a '!compute,!cog_create_user,!slcs' --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini -a '!compute,!cog_create_user,!slcs' --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini -a '!compute,!cog_create_user,!slcs' --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini -a '!compute,!cog_create_user,!slcs' --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini -a '!compute,!cog_create_user,!slcs' --with-html --with-id

echo -e "\n\n********************** AS THE MAN ON A NODE WITH SLCS *************************\n\n"
nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini -a '!compute,!cog_create_user' --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini -a '!compute,!cog_create_user' --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini -a '!compute,!cog_create_user' --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini -a '!compute,!cog_create_user' --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini -a '!compute,!cog_create_user' --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini -a '!compute,!cog_create_user' --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini -a '!compute,!cog_create_user' --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini -a '!compute,!cog_create_user' --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini -a '!compute,!cog_create_user' --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini -a '!compute,!cog_create_user' --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini -a '!compute,!cog_create_user' --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini -a '!compute,!cog_create_user' --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini -a '!compute,!cog_create_user' --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini -a '!compute,!cog_create_user' --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini -a '!compute,!cog_create_user' --with-html --with-id

echo -e "\n\n********************** ALL ON A NODE WITHOUT SLCS *************************\n\n"
nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini --with-html --with-id ; nosetests -v --nocapture --nologcapture --tc-file my_config_prod.ini --with-html --with-id

echo -e "\n\n********************** ALL ON A NODE SLCS ABLE *************************\n\n"
nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini --with-html --with-id; nosetests -v --nocapture --nologcapture --tc-file my_config_dev.ini --with-html --with-id